name: Ubuntu (latest)

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

env:
  # A workaround for long FQDN names provided by GitHub actions.
  FQDN: "localhost"

jobs:
  lint: # from lint.yml
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install linters
      run: |
        python -m pip install --upgrade pip
        pip install -r linters-requirements.txt 
    - name: Lint with OpenFL-specific rules
      run: bash shell/lint.sh

  pytest-coverage: # from pytest_coverage.yml
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage
        pip install -r test-requirements.txt
        pip install .
    - name: Test with pytest and report code coverage
      run: |
        coverage run -m pytest -rA
        coverage report
  
  cli:
    needs: [lint, pytest-coverage]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Test TaskRunner API
        run: |
          python -m tests.github.test_hello_federation --template keras_cnn_mnist --fed_workspace aggregator --col1 col1 --col2 col2  --rounds-to-train 3 --save-model output_model
